### PR TITLE
Bunch of QOL updates to auth on frontend

### LINKED ISSUE #34: Add feedback upon pressing log in, register, or logout
We should use a [`Toast`](https://ui.shadcn.com/docs/components/toast) component or maybe [`Sonner`](https://ui.shadcn.com/docs/components/sonner) to appear whenever an error or success occurs on major transactions.

### LINKED ISSUE #67: Make login with either username or email possible

### PR DESCRIPTION
**Pull request by alex-305**
- Closes #67 
- Closes #34

### CODE REVIEW

**Review by sama305 — APPROVED** [review]

**Review by sama305 — COMMENTED** [review]
When testing this I noticed it reverts the auto-logging in from #65. If we add code to reload the page after register, the toast disappears, so we need to find a way to maybe load the toast after reload or something

**Comment by alex-305** [comment]
Fixed merge issues, refactored auth logic in to useAuth() hook along with
- closes #69

**Review by sama305 — CHANGES_REQUESTED** [review]
We never use `scripts/js/csrf.ts`. Can we delete it?

**Review by sama305 — APPROVED** [review]
lgtm

**Pull request merged**
